### ISSUE TITLE
ril is broken

### ISSUE THREAD

**Issue by ranstar74** [ranstar74/android_device_xiaomi-nikel#6]

**Comment by jorgeiba97** [comment]
Any progress with RIL?

**Comment by ranstar74** [comment]
i've collected all ril blobs(theres alot really),but we need patchs also,im testing it now,it's going a bit slowly,because i need to recompile every time,and it takes about 2,5hr for me.so just wait,it may take some time.

**Comment by ranstar74** [comment]
FIXED!
